---
version: "3"
services:
   weechat:
      build: ./build
      image: docker-weechat-otr
      container_name: weechat-otr
      stdin_open: true
      tty: true
      ports:
         - "host relay port:container relay port"
      volumes:
         - "/path/to/host/.weechat:/home/weechat/.weechat"
      logging:
         driver: none
