version: "3"
services: 
   weechat: 
      build: .
      container_name: docker-weechat-otr
      stdin_open: true
      tty: true
      ports:
         # Add ports here for relay use
      volumes:
         - "/path/to/host/.weechat:/home/weechat/.weechat"
